### ISSUE TITLE
Can enter non numeric values

### ISSUE THREAD

**Issue by craiggeil** [fengyuanchen/vue-number-input#14]
I can enter e.....eeeee-----.....eeee and the control accepts this a valid entry

**Comment by fengyuanchen** [comment]
Are you sure? What's the browser and version?

**Comment by craiggeil** [comment]
Windows 10 -- Chrome 
![image](https://user-images.githubusercontent.com/30805831/57088742-8c9eff00-6cc8-11e9-8a82-bb8acf03438e.png)
 From your demo page:
![image](https://user-images.githubusercontent.com/30805831/57088841-bc4e0700-6cc8-11e9-868f-5cc254788633.png)

**Comment by fengyuanchen** [comment]
This is the native behaviour of the [`<input type="number">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) element.

**Comment by fengyuanchen** [comment]
BTW, `e`, `.` and `-` are valid number signs.
