### ISSUE TITLE
Decimal precision seperator

### ISSUE THREAD

**Issue by ErcinDedeoglu** [fengyuanchen/vue-number-input#15]
How to change decimal precision seperator dot (.) to comma (,)?

**Comment by fengyuanchen** [comment]
This component uses the native [`<input type="number">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) element for inputting and it does not support comma as the decimal precision separator.

**Comment by ErcinDedeoglu** [comment]
it should use it. because every country have their own cultures... why you closed the issue without my opinion?

**Comment by fengyuanchen** [comment]
I'm sorry, I mean this component will not support that feature.
