### ISSUE TITLE
System number input buttons are visible in Firefox on Ubuntu

### ISSUE THREAD

**Issue by mkasprz** [fengyuanchen/vue-number-input#17]
Hi.
![Screenshoot](https://user-images.githubusercontent.com/11790013/65776584-bc9ce200-e142-11e9-868f-39094b899a8e.png)
I believe the system buttons should not be visible. Looks like a missing CSS rule to me, or is it intentional?

**Comment by mkasprz** [comment]
Could You provide an explanation why You decided to close this issue?

**Comment by mkasprz** [comment]
Ok, sorry, I see You pushed a commit to fix it, thank You. Unfortunately in the demo the those buttons are still visible.

**Comment by fengyuanchen** [comment]
This change does not release yet.

**Comment by mkasprz** [comment]
Ok, I understand, thank You. As it seems already released I confirm that it works correctly. Thank You again!
