### ISSUE TITLE
@change triggers when the component is loaded

### ISSUE THREAD

**Issue by TheAndroidGuy** [fengyuanchen/vue-number-input#21]
Hello, thank you for this awesome component.
I noticed that @change triggers when the component is loaded. If there are a lot of instances of `number-input` on the page and there is some API call assigned to `@change` it will trigger the API call for each instance of the component.

**Comment by vanphong1310** [comment]
The function of change event will be received two arguments (newValue, oldValue), you can check if oldValue is not NaN then do whatever you want.

**Comment by TheAndroidGuy** [comment]
@vanphong1310 Thank you, that works.

**Comment by tshafer** [comment]
I am having the same problem. As I log it out oldValue is always filled out. I never get it to be NaN
