### ISSUE TITLE
"round" function not looking for step

### ISSUE THREAD

**Issue by piotrekcyk** [fengyuanchen/vue-number-input#22]
`<number-input v-model="costs" :min="0" :step="0.01" rounded></number-input>`
When we out input it rounded value to integer, not to float with step `0.01`

In this case controls also not working.

I think it's bug.

**Comment by fengyuanchen** [comment]
If you enable the `rounded` prop, the value will be normalized by the `Math.round` function. So it is not a bug I think. I am afraid it is not supporting decimals.
