### ISSUE TITLE
Placeholder was hide by zero also when v-model variable has null

### ISSUE THREAD

**Issue by piotrekcyk** [fengyuanchen/vue-number-input#23]
I have simple input like: `<number-input v-model="props.item.price" placeholder="Price by kilometer" :min="0" :step="0.01"></number-input>`

And it's look like: 
![image](https://user-images.githubusercontent.com/17705520/74173721-e444a080-4c32-11ea-970c-ebe82375fa07.png)

Only first element has value, others are null.

My question is: **Where is my placeholder :cry:**

**Comment by piotrekcyk** [comment]
ok, i have some bypass 
![image](https://user-images.githubusercontent.com/17705520/74215710-4688ba00-4ca2-11ea-80fb-474532fc89cb.png)

**Comment by fengyuanchen** [comment]
The given value should be a number (`typeof value === 'number'`).
