### ISSUE TITLE
Change icons for plus and minus

### ISSUE THREAD

**Issue by shaks786** [fengyuanchen/vue-number-input#26]
Hi, is it possible to change the icons for the plus and minus?

I've changed the border radius of input to 20px and now those icons are not rendering properly (they seem to overlap with the corners of the input)

Example:

![image](https://user-images.githubusercontent.com/2884611/98860035-fcb04880-245a-11eb-9896-0e80c10583c3.png)

**Comment by fengyuanchen** [comment]
Just override the CSS styles of the input buttons in your app.
