### ISSUE TITLE
Can't set to blank

### ISSUE THREAD

**Issue by jacobg** [fengyuanchen/vue-number-input#28]
Once a value is set on the input, it won't allow it to be deleted and set to null. Repro here:
https://fengyuanchen.github.io/vue-number-input/

This use case is important for optional values. A blank null value is a sentinel value which can signify to ignore whatever setting it represents.

**Comment by jacobg** [comment]
Thanks for this commit! Is it intentional that a blank value should be set to NaN rather than null?

**Comment by fengyuanchen** [comment]
The given value will be parsed by `parseFloat`, so a `null` value is available too:

```js
parseFloat(null); // NaN
parseFloat(undefined); // NaN
parseFloat(''); // NaN
parseFloat(NaN); // NaN
```

**Comment by jacobg** [comment]
My concern is that NaN is not a system-independent value, whereas a JSON null value is. Although `JSON.stringify(NaN) === "null"`, but we're still dealing with two different value types: `null` as bound by the application, and `NaN` as output by the component. So the application then needs to check for the presence of either value if it wants to know if the value is not set. It also can't rely on equality to determine whether the form is dirty.

**Comment by fengyuanchen** [comment]
In my opinion, as a **number input** component, the accept value and output value should be numbers, which is a common mode. You can search for others number input components for reference.
