### ISSUE TITLE
Propagate modelValue to parent component

### ISSUE THREAD

**Issue by matmu** [fengyuanchen/vue-number-input#30]
In my Vue 3 app I want to have a two-way binding for the vue-number-input value that is passed as a property from the parent component.  Propagating the value back to the parent component doesn't work, however.

**Parent component**:
```
<template>
  <TechnologyForm v-model:tti="tti"></TechnologyForm> 
</template>

<script>

import { ref } from 'vue'
import TechnologyForm from '@/components/TechnologyForm.vue'

export default {
   components: { 
      TechnologyForm
    },
   setup(){
      const tti = ref()

      return(tti)
   }
}
```

**Child component** `TechnologyForm `:
```
<template>
<vue-number-input :modelValue="tti" :min="1" @input="$emit('update:tti', $event.target.value)" placeholder="Years" inline controls rounded></vue-number-input>`
</template>

import VueNumberInput from '@chenfengyuan/vue-number-input'

export default {
    props: ['tti'],
    components: {
       VueNumberInput
    }
}
</script>
```

For other inputs it works fine, e.g. 
`<textarea :value="relevance" @input="$emit('update:relevance', $event.target.value)" class="form-control" id="relevance" rows="3"></textarea>`

**Comment by fengyuanchen** [comment]
It seems your child component missing the [`emits`](https://v3.vuejs.org/api/options-data.html#emits) option.

**Comment by matmu** [comment]
@fengyuanchen for other input fields in the same child component it works. The only difference I can see is that I am using `:modelValue` for `vue-number-input` and `:value` for the others.

**Comment by fengyuanchen** [comment]
Try to use the `update:model-value` event instead of `input` event.

**Comment by fengyuanchen** [comment]
Any online demo?
