### ISSUE TITLE
Prevent double tap and allow holding button down on mobile

### ISSUE THREAD

**Issue by kjyv** [fengyuanchen/vue-number-input#35]
On mobile devices, making larger value changes using the buttons is a bit tedious - e.g. when using a small step size like 0.1. When tapping multiple times, browsers zoom into the page (iOS at least) and holding down the button does not change the value repeatedly (and possibly get faster over time).
(adding CSS touch-action: manipulation works for me for tapping)

**Comment by fengyuanchen** [comment]
Just disable the click event on the parent element:

```html
<div @click.stop.prevent>
  <vue-number-input controls></vue-number-input>
</div>
```

**Comment by kjyv** [comment]
This might be a workaround, not a fix of the behavior of the control. This is not just useful in my specific case but for everyone using the widget
