### ISSUE TITLE
Can't write in input

### ISSUE THREAD

**Issue by jackleblack-kpt** [fengyuanchen/vue-number-input#5]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Can't write in the input.

## Expected behavior

Write in the input.

## Minimal reproduction of the problem with instructions

 `<number-input  v-model="value" :step="10" inlinecontrols></number-input>`

Without the "v-model" all works fine.

## Environment

<pre><code>
vue-number-input version: 5.0.1
vue-number-input version: 5.0.0
vue-number-input version: 4.0.1

Browser:
- [x] Chrome (desktop) version XX

Others:

**Comment by fengyuanchen** [comment]
Can not reappear... Any demo?

**Comment by jackleblack-kpt** [comment]
We use a @keydown event `@keydown="form.errors.clear($event.target.name);"` for clear error on keydown. There is a conflict between the two. Have you an idea ?

**Comment by jackleblack-kpt** [comment]
Not an issue from your plugin sorry.

The issue is in Vue. Any state change (modifying any data value) inside a keydown event will prevent the keydown input. See this example https://codesandbox.io/s/6zp3l523nr

I've checked and this behaviour changed from Vue 2.4.4 to 2.5.0.
